name: 自动同步到腾讯云 COS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取 GitHub 代码
        uses: actions/checkout@v4
      - name: 安装 COS 命令行工具
        run: sudo pip install coscmd
      - name: 配置 COS 工具
        env:
          SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          BUCKET: ${{ secrets.COS_BUCKET }}
          REGION: ${{ secrets.COS_REGION }}
        run: coscmd config -a  -s  -b  -r 
      - name: 同步文件到 COS
        run: coscmd upload -r ./tpt-file-share/HIS/ / --delete
